In [3]:
import numpy as np


np.array([1, 2, 3, 4])
np.arange(9, 30, 2)


array([ 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [4]:
np.linspace(0, 2 * np.pi, 5) #first two elements are the bounderies and then we say we want 5 elements evenly distributed

array([ 0.        ,  1.57079633,  3.14159265,  4.71238898,  6.28318531])

In [8]:
data = np.arange(9, 30)
print(data)
data[-2]
data[1: -2: 2]

[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


array([10, 12, 14, 16, 18, 20, 22, 24, 26])

In [10]:
#every array in numpy has a .shape property that gives the dimensions of the arrays
#the order are from last to first dimension, Z-Y-X

two_dim = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print(two_dim.shape) #first is the y dimension then the x dimension


(4, 3)


In [11]:
np.arange(36).reshape(4, 3, 3) #shape an array into one with different form and dimension, needs to make sure that the 
                                # number of elements equal the * of the dimensions 36 = 4 * 3 * 3
                                #in a two dimensional array, x = columns Y = rows

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [31]:
a = np.arange(11, 36).reshape(5, 5)
a
print(a[0, 1:-1]) #y=0 1<=x<last so first row column 2-3-4 (index 1 2 3)
print(a[1:-1, 0]) # first column row 2-3-4
print(a[::2, ::2]) #every second column in every second row
print(a[:, 1])   #column 2 (index1) all rows, so all column 2
#print(a[y axis, x axis])

[12 13 14]
[16 21 26]
[[11 13 15]
 [21 23 25]
 [31 33 35]]
[12 17 22 27 32]


In [33]:
800*1024

819200